"use client";

import { useEffect, useState } from "react";
import { doc, getDoc } from "firebase/firestore";
import { QRCodeSVG } from "qrcode.react";
import { db } from "../../../lib/firebase";

type VerificationRecord = {
  displayName?: string;
  status?: string;
  verificationStatus?: string;
  cardStatus?: string;
};

export default function VerifyPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const [id, setId] = useState("");
  const [record, setRecord] = useState<VerificationRecord | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    let cancelled = false;

    params.then(({ id: rawId }) => {
      const normalizedId = decodeURIComponent(rawId).trim();
      if (cancelled) return;
      setId(normalizedId);

      if (!normalizedId) {
        setLoading(false);
        return;
      }

      getDoc(doc(db, "public_verifications", normalizedId))
        .then((snapshot) => {
          if (cancelled) return;
          setRecord(snapshot.exists() ? (snapshot.data() as VerificationRecord) : null);
          setLoading(false);
        })
        .catch(() => {
          if (cancelled) return;
          setError(true);
          setLoading(false);
        });
    });

    return () => {
      cancelled = true;
    };
  }, [params]);

  const verificationUrl = typeof window !== "undefined"
    ? `${window.location.origin}/verify/${encodeURIComponent(id)}`
    : `/verify/${encodeURIComponent(id)}`;

  if (loading) {
    return (
      <main className="verify-shell">
        <section className="verify-card">
          <div className="brand">iAmHuman</div>
          <span className="badge">CHECKING</span>
          <h1 className="title">Checking verification</h1>
          <p className="subtitle">Looking up this iAmHuman verification record.</p>
        </section>
      </main>
    );
  }

  if (error) {
    return (
      <main className="verify-shell">
        <section className="verify-card error">
          <div className="brand">iAmHuman</div>
          <span className="badge">UNAVAILABLE</span>
          <h1 className="title">Verification unavailable</h1>
          <p className="subtitle">The verification service could not be reached. Please try again.</p>
          <div className="profile">
            <div className="profile-label">Verification ID</div>
            <div className="profile-value">{id || "Missing ID"}</div>
          </div>
        </section>
      </main>
    );
  }

  const isVerified = record?.status === "ACTIVE";

  if (!record || !isVerified) {
    return (
      <main className="verify-shell">
        <section className="verify-card error">
          <div className="brand">iAmHuman</div>
          <span className="badge">NOT VERIFIED</span>
          <h1 className="title">Verification unavailable</h1>
          <p className="subtitle">No active iAmHuman verification record was found for this ID.</p>
          <div className="profile">
            <div className="profile-label">Verification ID</div>
            <div className="profile-value">{id || "Missing ID"}</div>
            {record?.status && (
              <>
                <div className="profile-label">Card status</div>
                <div className="profile-value">{record.status}</div>
              </>
            )}
          </div>
          <div className="footer">This result is generated by the iAmHuman verification system.</div>
        </section>
      </main>
    );
  }

  return (
    <main className="verify-shell">
      <section className="verify-card">
        <div className="brand">iAmHuman</div>
        <span className="badge">✓ VERIFIED</span>
        <h1 className="title">Human verified</h1>
        <p className="subtitle">This iAmHuman verification record is active.</p>

        <div className="profile">
          {record.displayName && <div className="profile-name">{record.displayName}</div>}
          <div className="profile-label">Verification ID</div>
          <div className="profile-value">{id}</div>
          <div className="profile-label">Card status</div>
          <div className="profile-value">{record.cardStatus || "ACTIVE"}</div>
          <div className="profile-label">Verification status</div>
          <div className="profile-value">{record.verificationStatus || "VERIFIED"}</div>
        </div>

        <div className="qr-wrap">
          <QRCodeSVG value={verificationUrl} size={180} includeMargin />
        </div>
        <div className="url">{verificationUrl}</div>
        <div className="footer">Scan the QR code or tap an iAmHuman NFC card to open this verification record.</div>
      </section>
    </main>
  );
}
