import { QRCodeSVG } from "qrcode.react";

const DEMO_ID = "DEMO001";

function getVerificationUrl(id: string) {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
  return `${baseUrl}/verify/${encodeURIComponent(id)}`;
}

export default async function VerifyPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const normalizedId = decodeURIComponent(id).trim();
  const isDemo = normalizedId.toUpperCase() === DEMO_ID;
  const verificationUrl = getVerificationUrl(normalizedId);

  if (!isDemo) {
    return (
      <main className="verify-shell">
        <section className="verify-card error">
          <div className="brand">iAmHuman</div>
          <span className="badge">NOT VERIFIED</span>
          <h1 className="title">Verification unavailable</h1>
          <p className="subtitle">
            No active iAmHuman verification record was found for this ID.
          </p>
          <div className="profile">
            <div className="profile-label">Verification ID</div>
            <div className="profile-value">{normalizedId || "Missing ID"}</div>
          </div>
          <div className="footer">
            This result is generated by the iAmHuman verification system.
          </div>
        </section>
      </main>
    );
  }

  return (
    <main className="verify-shell">
      <section className="verify-card">
        <div className="brand">iAmHuman</div>
        <span className="badge">✓ VERIFIED</span>
        <h1 className="title">Human verified</h1>
        <p className="subtitle">
          This iAmHuman verification record is active.
        </p>

        <div className="profile">
          <div className="profile-name">iAmHuman Demo</div>
          <div className="profile-label">Verification ID</div>
          <div className="profile-value">{normalizedId}</div>

          <div className="profile-label">Card status</div>
          <div className="profile-value">ACTIVE</div>

          <div className="profile-label">Verification status</div>
          <div className="profile-value">VERIFIED</div>
        </div>

        <div className="qr-wrap">
          <QRCodeSVG value={verificationUrl} size={180} includeMargin />
        </div>
        <div className="url">{verificationUrl}</div>

        <div className="footer">
          Scan the QR code or tap an iAmHuman NFC card to open this verification record.
        </div>
      </section>
    </main>
  );
}
